/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.archivos;

import InterfazTabla.TablaCatePro;
import ejemplo.SQLPrincipal;
import ejemplo.servicio;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class CategoriaDProductos extends javax.swing.JInternalFrame {
        private ResultSet datos;
        private int bandera1=0;
        private int bandera2=0;
        private int banderaInsert=1;
        private int banderaUpdate=1;
        private PreparedStatement ps;
        private servicio ser;
    /**
     * Creates new form CategoriaDProductos
     */
    public CategoriaDProductos() {
        initComponents();
        jLTx1.setText("");
        jLTx2.setText("");
        JBGrabar.setEnabled(false);
        JBCancelar.setEnabled(false);
        ser= new servicio();
        ps=ser.Querys("SELECT * FROM ingru");
            try {
                datos=ser.Consultar(ps);
                 if(datos.next()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                 }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jBInicio = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jBAdicionar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        JBGrabar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxCod = new javax.swing.JTextField();
        TxDes = new javax.swing.JTextField();
        TxCuenta = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLTx1 = new javax.swing.JLabel();
        jLTx2 = new javax.swing.JLabel();

        setTitle("CATEGORIA DE PRODUCTOS");

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jBInicio.setText("Inicio");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBAnterior.setText("Anterior");
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        jBProximo.setText("Próximo");
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });

        jBUltimo.setText("Ultimo");
        jBUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBUltimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInicio)
                    .addComponent(jBAnterior)
                    .addComponent(jBProximo)
                    .addComponent(jBUltimo))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        JBGrabar.setText("Grabar");
        JBGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGrabarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscar)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionar)
                    .addComponent(jBEliminar)
                    .addComponent(JBGrabar)
                    .addComponent(JBCancelar)
                    .addComponent(jBBuscar)
                    .addComponent(jBModificar))
                .addContainerGap())
        );

        jLabel1.setText("Codigo");

        jLabel2.setText("Descripción");

        jLabel3.setText("Cuenta Contable Inventario");

        TxCod.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TxCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxCodKeyPressed(evt);
            }
        });

        TxDes.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        TxCuenta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jButton12.setBackground(new java.awt.Color(255, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Salir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLTx1.setForeground(new java.awt.Color(253, 9, 9));
        jLTx1.setText("El Campo de Codigo no puede quedar Vacio.");

        jLTx2.setForeground(new java.awt.Color(255, 0, 0));
        jLTx2.setText("Ingrese una descripción.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxDes, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTx1)
                            .addComponent(jLTx2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addComponent(TxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLTx1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLTx2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(8, 8, 8)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBAdicionar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        TxCod.setText("");
        TxDes.setText("");
        TxCuenta.setText("");
        if(banderaInsert==1){
           banderaInsert=0; 
        }
        
        
     
        
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        TxCod.setEditable(true);
        jBInicio.setEnabled(true);
        jBAnterior.setEnabled(true);
        jBProximo.setEnabled(true);
        jBUltimo.setEnabled(true);
        jBAdicionar.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscar.setEnabled(true);
        JBGrabar.setEnabled(false);
        JBCancelar.setEnabled(false);
            try {
                
                if(!datos.wasNull()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        try {
                if(datos.first()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                    bandera2=0;
                }
                else{
                    TxCod.setText(datos.getString(""));
                    TxDes.setText(datos.getString(""));
                    TxCuenta.setText(datos.getString(""));  
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoActionPerformed
         try {
                if(datos.last()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                    bandera1=0;
                }
                else{
                    TxCod.setText(datos.getString(""));
                    TxDes.setText(datos.getString(""));
                    TxCuenta.setText(datos.getString(""));  
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBUltimoActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
         try {
             if(bandera2==1){
                 datos.next();
             }
             if(bandera1==0){
                if(datos.next()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                    bandera2=0;
                }
                else{
                    bandera1=1;
                }
             }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBProximoActionPerformed

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnteriorActionPerformed
        try { 
            if(bandera1==1){
                datos.previous();
            }
            if(bandera2==0){
                if(datos.previous()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                    bandera1=0;
                }
                else{
                  bandera2=1;   
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jBAnteriorActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            try {
                ser.desconectar(datos);
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
            this.setVisible(false);
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ProductoXBodega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void JBGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGrabarActionPerformed
        if(banderaInsert==0){
            if(TxCod.getText().isEmpty()){
                jLTx1.setText("El Campo de Codigo no puede quedar Vacio.");
                return;
            }
            if(TxDes.getText().isEmpty()){
                jLTx2.setText("Ingrese una descripción.");
                return;
            }
            if(TxCod.getText().length()>3){
                jLTx1.setText("El codigo introducido excede los 3 caracteres.");
                return;
            }
            try {
                ps=ser.Querys("INSERT INTO ingru (codgru,desgru,codigoinv)values(?,?,?)");
                ps.setString(1,TxCod.getText().toString());
                ps.setString(2,TxDes.getText().toString());
                ps.setString(3,TxCuenta.getText().toString());
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT codgru,desgru,codigoinv FROM ingru ");
                datos = ser.Consultar(ps);                    
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode()==1062){
                    Frame f = JOptionPane.getFrameForComponent(this);
                    CodigoExistente dialog = new CodigoExistente(f, true);
                    dialog.setVisible(true);
                    TxCod.setText("");
                    TxDes.setText("");
                    TxCuenta.setText("");  
                    jLTx1.setText("");
                    jLTx2.setText("");
                    return;
                }
            }
            banderaInsert=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBAdicionar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            jLTx1.setText("");
            jLTx2.setText("");
        }
        if(banderaUpdate==0){
             if(TxDes.getText().isEmpty()){
                 jLTx2.setText("Ingrese una descripción.");
                 return;
             }
             try {
                ps=ser.Querys("UPDATE ingru SET desgru = ?, codigoinv = ? where codgru = ? ");
                ps.setString(1,TxDes.getText());
                ps.setString(2,TxCuenta.getText());
                ps.setString(3,TxCod.getText());
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT codgru,desgru,codigoinv FROM ingru ");
                datos=ser.Consultar(ps);
                 try {
                    if(datos.next()){  
                        TxCod.setText(datos.getString("codgru"));
                        TxDes.setText(datos.getString("desgru"));
                        TxCuenta.setText(datos.getString("codigoinv"));
                        bandera1=0;
                
                    }
                    } catch (SQLException ex) {
                        Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                                
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            banderaUpdate=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBAdicionar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            TxCod.setEditable(true);
            jLTx2.setText("");
            
        }
    }//GEN-LAST:event_JBGrabarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBAdicionar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);     
        TxCod.setEditable(false);
        banderaUpdate=0;
         
       
    }//GEN-LAST:event_jBModificarActionPerformed

    private void TxCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCodKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
      
        
        try {
            if(datos.next()){  
                TxCod.setText(datos.getString("codgru"));
                TxDes.setText(datos.getString("desgru"));
                TxCuenta.setText(datos.getString("codigoinv"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_TxCodKeyPressed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
          Frame f = JOptionPane.getFrameForComponent(this);
              BorrarFila dialog = new BorrarFila(f, true);
              dialog.setVisible(true);
              if(dialog.getReturnStatus()==dialog.RET_OK){
              ps =ser.Querys("DELETE FROM ingru where codgru=?");
              try {
                  ps.setString(1,TxCod.getText().toString());
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              try {
                  ser.InsBorrElim(ps);
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              ps=ser.Querys("SELECT * FROM ingru");
              try {
                 datos=ser.Consultar(ps);
                 if(datos.next()){
                    TxCod.setText(datos.getString("codgru"));
                    TxDes.setText(datos.getString("desgru"));
                    TxCuenta.setText(datos.getString("codigoinv"));
                 }
              } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                }                        
                    }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        TablaCatePro ventanaP= new TablaCatePro();
        
        centrarPantallaInternal(ventanaP);
        ventanaP.toFront();
        ventanaP.setVisible(true);
    }//GEN-LAST:event_jBBuscarActionPerformed
    
    public void centrarPantallaInternal(JInternalFrame ventana){
        int x =(PrinciPAL.DeskPanelP.getWidth()/2)-ventana.getWidth()/2;
        int y =(PrinciPAL.DeskPanelP.getHeight()/2)-ventana.getHeight()/2;
        if(ventana.isShowing()){
            ventana.setLocation(x, y);
        }else{
            PrinciPAL.DeskPanelP.add(ventana);
            ventana.setLocation(x, y);
            ventana.setVisible(true);
        } 
    };
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBGrabar;
    public static javax.swing.JTextField TxCod;
    public static javax.swing.JTextField TxCuenta;
    public static javax.swing.JTextField TxDes;
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBProximo;
    private javax.swing.JButton jBUltimo;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLTx1;
    private javax.swing.JLabel jLTx2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
