/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.archivos;

import InterfazTabla.TablaCatePro;
import InterfazTabla.TablaCatePro1;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import ejemplo.*;
import static interfaz.archivos.CategoriaDProductos.TxCod;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class LineaDProductos extends javax.swing.JInternalFrame {
    private ResultSet datos;
    private PreparedStatement ps;
    private int bandera2=0;
    private int bandera1=0;
    private int banderaInsert=1;
    private int banderaUpdate=1;
    private servicio ser;
    private int opcion;
    /**
     * Creates new form LineaDProductos
     */
    public LineaDProductos() {
        
            initComponents();
            ser= new servicio();
            JBLupa.setVisible(false);
            Grupo.add(JBSi);
            Grupo.add(jBNO);
            jBNO.setSelected(true);
            TxCod.setEditable(false);
            TxDes.setEditable(false);
            CodCat.setEditable(false);
            DesCat.setEditable(false);
            JBSi.setEnabled(false);
            jBNO.setEnabled(false);
            servicio ser= new servicio();
            try {
            ps=ser.Querys("SELECT inlin.codlin,inlin.deslin,inlin.propina,inlin.codgru,ingru.desgru FROM inlin,ingru where inlin.codgru=ingru.codgru ");
            datos=ser.Consultar(ps);
            try {
                if(datos.next()){
                    TxCod.setText(datos.getString("codlin"));  
                    TxDes.setText(datos.getString("deslin"));
                    CodCat.setText(datos.getString("codgru"));
                    DesCat.setText(datos.getString("desgru"));
                    CodCat.setEditable(false);
                    DesCat.setEditable(false);
                    int opt = datos.getInt("propina");
                    if(opt==1){
                       JBSi.setSelected(true);
                    }
                    else{
                        jBNO.setSelected(true);   
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        JBGrabar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jBInicio = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxCod = new javax.swing.JTextField();
        TxDes = new javax.swing.JTextField();
        CodCat = new javax.swing.JTextField();
        JBSi = new javax.swing.JRadioButton();
        jBNO = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        DesCat = new javax.swing.JTextField();
        JBLupa = new javax.swing.JButton();
        jLTx1 = new javax.swing.JLabel();
        jLTx2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setTitle("LINEA  DE PRODUCTOS");

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jBNuevo.setText("Adicionar");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        JBGrabar.setText("Grabar");
        JBGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGrabarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscar)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBEliminar)
                        .addComponent(JBGrabar)
                        .addComponent(JBCancelar)
                        .addComponent(jBBuscar)
                        .addComponent(jBModificar)))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jBInicio.setText("Inicio");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBAnterior.setText("Anterior");
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        jBProximo.setText("Próximo");
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });

        jBUltimo.setText("Ultimo");
        jBUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBUltimo)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInicio)
                    .addComponent(jBAnterior)
                    .addComponent(jBProximo)
                    .addComponent(jBUltimo))
                .addContainerGap())
        );

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Salir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Descripción");

        jLabel3.setText("Categoria ");

        TxCod.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        TxDes.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        CodCat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        JBSi.setText("Si");

        jBNO.setText("No");

        jLabel5.setText("Aplicar Propina ");

        DesCat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        JBLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier12 (1).png"))); // NOI18N
        JBLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLupaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 2, Short.MAX_VALUE)
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLTx1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBNO))
                            .addComponent(TxDes, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodCat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DesCat))
                            .addComponent(jLTx2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBLupa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTx1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLTx2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBLupa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(CodCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DesCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBSi)
                        .addComponent(jBNO))
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        TxCod.setText("");  
        TxDes.setText("");
        CodCat.setText("");
        DesCat.setText("");
        JBLupa.setVisible(true);
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        CodCat.setEditable(true);
        DesCat.setEditable(true);
        TxCod.setEditable(true);
        TxDes.setEditable(true);
        JBSi.setEnabled(true);
        jBNO.setEnabled(true);
        banderaInsert=0;
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        JBLupa.setVisible(false);
        jBInicio.setEnabled(true);
        jBAnterior.setEnabled(true);
        jBProximo.setEnabled(true);
        jBUltimo.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscar.setEnabled(true);
        JBGrabar.setEnabled(false);
        JBCancelar.setEnabled(false);
        TxCod.setEditable(false);
        TxDes.setEditable(false);
        CodCat.setEditable(false);
        DesCat.setEditable(false);
        JBSi.setEnabled(false);
        jBNO.setEnabled(false);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            this.setVisible(false);
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ProductoXBodega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        JBLupa.setVisible(true);
        TxDes.setEditable(true);
        CodCat.setEditable(true);
        DesCat.setEditable(true);
        JBSi.setEnabled(true);
        jBNO.setEnabled(true);
        banderaUpdate=0;
        
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
      try {
                if(datos.first()){
                    TxCod.setText(datos.getString("codlin"));  
                    TxDes.setText(datos.getString("deslin"));
                    CodCat.setText(datos.getString("codgru"));
                    DesCat.setText(datos.getString("desgru"));
                    int opt = datos.getInt("propina");
                    if(opt==1){
                       JBSi.setSelected(true);
                    }
                    else{
                        jBNO.setSelected(true);   
                    }
                    bandera2=0;
                }
                else{
                    TxCod.setText("");
                    TxDes.setText("");
                    CodCat.setText("");
                    DesCat.setText(""); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnteriorActionPerformed
        try {  
            if(bandera1==1){
                datos.previous();
            }
            if(bandera2==0){
                if(datos.previous()){
                    TxCod.setText(datos.getString("codlin"));  
                    TxDes.setText(datos.getString("deslin"));
                    CodCat.setText(datos.getString("codgru"));
                    DesCat.setText(datos.getString("desgru"));
                    int opt = datos.getInt("propina");
                    if(opt==1){
                       JBSi.setSelected(true);
                    }
                    else{
                        jBNO.setSelected(true);   
                    }
                    bandera1=0;
                }
                else{
                  bandera2=1;   
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBAnteriorActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
        try {
            if(bandera2==1){
                datos.next();
            }
             if(bandera1==0){
                if(datos.next()){
                    TxCod.setText(datos.getString("codlin"));  
                    TxDes.setText(datos.getString("deslin"));
                    CodCat.setText(datos.getString("codgru"));
                    DesCat.setText(datos.getString("desgru"));
                    int opt = datos.getInt("propina");
                    if(opt==1){
                       JBSi.setSelected(true);
                    }
                    else{
                        jBNO.setSelected(true);   
                    }
                    bandera2=0;
                }
                else{
                    bandera1=1;
                }
             }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBProximoActionPerformed

    private void jBUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoActionPerformed
        try {
                if(datos.last()){
                    TxCod.setText(datos.getString("codlin"));  
                    TxDes.setText(datos.getString("deslin"));
                    CodCat.setText(datos.getString("codgru"));
                    DesCat.setText(datos.getString("desgru"));
                    int opt = datos.getInt("propina");
                    if(opt==1){
                       JBSi.setSelected(true);
                    }
                    else{
                        jBNO.setSelected(true);   
                    }
                    bandera1=0;
                }
                else{
                    TxCod.setText("");
                    TxDes.setText("");
                    CodCat.setText("");
                    DesCat.setText("");
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBUltimoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
       
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void JBLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLupaActionPerformed

        TablaCatePro1 ventanaP= new TablaCatePro1();
        centrarPantallaInternal(ventanaP);
        ventanaP.toFront();
        ventanaP.setVisible(true);
    }//GEN-LAST:event_JBLupaActionPerformed

    private void JBGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGrabarActionPerformed
      if(banderaInsert==0){
            if(TxCod.getText().isEmpty()){
                jLTx1.setText("El Campo de Codigo no puede quedar Vacio.");
                return;
            }
            if(TxDes.getText().isEmpty()){
                jLTx2.setText("Ingrese una descripción.");
                return;
            }
            if(TxCod.getText().length()>3){
                jLTx1.setText("El codigo introducido excede los 3 caracteres.");
                return;
            }
            try {
                if(JBSi.isSelected()){
                    opcion= 1;
                }
                else{ 
                    opcion=0;
                }
                ps=ser.Querys("INSERT INTO inlin (codlin,deslin,codgru,propina)values(?,?,?,?)");
                ps.setString(1,TxCod.getText());
                ps.setString(2,TxDes.getText());
                ps.setString(3,CodCat.getText());
                ps.setInt(4,opcion);
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT inlin.codlin,inlin.deslin,inlin.propina,inlin.codgru,ingru.desgru FROM inlin,ingru where inlin.codgru=ingru.codgru ");
                datos = ser.Consultar(ps);                    
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode()==1062){
                    Frame f = JOptionPane.getFrameForComponent(this);
                    CodigoExistente dialog = new CodigoExistente(f, true);
                    dialog.setVisible(true);
                    TxCod.setText("");
                    TxDes.setText("");
                    jLTx1.setText("");
                    jLTx2.setText("");
                    return;
                }
            }
            banderaInsert=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBNuevo.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            jLTx1.setText("");
            jLTx2.setText("");
            TxCod.setEditable(false);
            TxDes.setEditable(false);
            CodCat.setEditable(false);
            DesCat.setEditable(false);
            JBSi.setEnabled(false);
            jBNO.setEnabled(false);     
      }
      
       if(banderaUpdate==0){
             if(TxDes.getText().isEmpty()){
                 jLTx2.setText("Ingrese una descripción.");
                 return;
             }
             try {
                 if(JBSi.isSelected()){
                    opcion= 1;
                }
                else{ 
                    opcion=0;
                }
                ps=ser.Querys("UPDATE inlin SET deslin = ?,codgru=?,propina=? where codlin = ? ");
                ps.setString(1,TxDes.getText());
                ps.setString(2,CodCat.getText());
                ps.setInt(3,opcion);
                ps.setString(4,TxCod.getText());
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT inlin.codlin,inlin.deslin,inlin.propina,inlin.codgru,ingru.desgru FROM inlin,ingru where inlin.codgru=ingru.codgru");
                datos=ser.Consultar(ps);
                 try {
                    if(datos.next()){  
                        TxCod.setText(datos.getString("codlin"));  
                        TxDes.setText(datos.getString("deslin"));
                        CodCat.setText(datos.getString("codgru"));
                        DesCat.setText(datos.getString("desgru"));
                        CodCat.setEditable(false);
                        DesCat.setEditable(false);
                        int opt = datos.getInt("propina");
                        if(opt==1){
                            JBSi.setSelected(true);
                         }
                         else{
                             jBNO.setSelected(true);   
                        }
                        
                        bandera2=0;
                        bandera1=0;
                    }
                    } catch (SQLException ex) {
                        Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                                
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            banderaUpdate=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBNuevo.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            TxCod.setEditable(true);
            jLTx2.setText("");
            TxCod.setEditable(false);
            TxDes.setEditable(false);
            CodCat.setEditable(false);
            DesCat.setEditable(false);
            JBSi.setEnabled(false);
            jBNO.setEnabled(false); 
            
        }
        
        
        
    }//GEN-LAST:event_JBGrabarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
       Frame f = JOptionPane.getFrameForComponent(this);
              BorrarFila dialog = new BorrarFila(f, true);
              dialog.setVisible(true);
              if(dialog.getReturnStatus()==BorrarFila.RET_OK){
              ps =ser.Querys("DELETE FROM inlin where codlin=?");
              try {
                  ps.setString(1,TxCod.getText());
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              try {
                  ser.InsBorrElim(ps);
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              ps=ser.Querys("SELECT inlin.codlin,inlin.deslin,inlin.propina,inlin.codgru,ingru.desgru FROM inlin,ingru where inlin.codgru=ingru.codgru");
           try {
               datos=ser.Consultar(ps);
           } catch (SQLException ex) {
               Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
           }
                 try {
                    if(datos.next()){  
                        TxCod.setText(datos.getString("codlin"));  
                        TxDes.setText(datos.getString("deslin"));
                        CodCat.setText(datos.getString("codgru"));
                        DesCat.setText(datos.getString("desgru"));
                        CodCat.setEditable(false);
                        DesCat.setEditable(false);
                        int opt = datos.getInt("propina");
                        if(opt==1){
                            JBSi.setSelected(true);
                         }
                         else{
                             jBNO.setSelected(true);   
                        }
                        bandera2=0;
                        bandera1=0;
                  
                 }
              } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                }                        
    }                 
        
        
    }//GEN-LAST:event_jBEliminarActionPerformed
    public void centrarPantallaInternal(JInternalFrame ventana){
        int x =(PrinciPAL.DeskPanelP.getWidth()/2)-ventana.getWidth()/2;
        int y =(PrinciPAL.DeskPanelP.getHeight()/2)-ventana.getHeight()/2;
        if(ventana.isShowing()){
            ventana.setLocation(x, y);
        }else{
            PrinciPAL.DeskPanelP.add(ventana);
            ventana.setLocation(x, y);
            ventana.setVisible(true);
        } 
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField CodCat;
    public static javax.swing.JTextField DesCat;
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBGrabar;
    private javax.swing.JButton JBLupa;
    public static javax.swing.JRadioButton JBSi;
    public static javax.swing.JTextField TxCod;
    public static javax.swing.JTextField TxDes;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBModificar;
    public static javax.swing.JRadioButton jBNO;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBProximo;
    private javax.swing.JButton jBUltimo;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLTx1;
    private javax.swing.JLabel jLTx2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
