/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.archivos;

import ejemplo.servicio;
import static interfaz.archivos.CategoriaDProductos.TxCod;
import static interfaz.archivos.CategoriaDProductos.TxCuenta;
import static interfaz.archivos.CategoriaDProductos.TxDes;
import java.awt.Frame;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class MarcasProducto extends javax.swing.JInternalFrame {
    private servicio ser;
    private ResultSet datos;
    private PreparedStatement ps;
    private int bandera1 =0;
    private int bandera2=0;
    private int banderaInsert=1;
    private int banderaUpdate=1;
    

    /**
     * Creates new form MarcasProducto
     */
    public MarcasProducto() {
        initComponents();
        cod.setEditable(false);
        des.setEditable(false);
         ser= new servicio();
         ps=ser.Querys("SELECT * FROM inmar");
            try {
                datos=ser.Consultar(ps);
                 if(datos.next()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                 }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jBAdicionar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        JBGrabar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jBInicio = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        cod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLTx2 = new javax.swing.JLabel();
        jLTx1 = new javax.swing.JLabel();

        setTitle("MARCAS DE PRODUCTOS");

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        JBGrabar.setText("Grabar");
        JBGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGrabarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscar)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionar)
                    .addComponent(jBEliminar)
                    .addComponent(JBGrabar)
                    .addComponent(JBCancelar)
                    .addComponent(jBBuscar)
                    .addComponent(jBModificar))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jBInicio.setText("Inicio");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBAnterior.setText("Anterior");
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        jBProximo.setText("Próximo");
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });

        jBUltimo.setText("Ultimo");
        jBUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBUltimo)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInicio)
                    .addComponent(jBAnterior)
                    .addComponent(jBProximo)
                    .addComponent(jBUltimo))
                .addContainerGap())
        );

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Salir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Descripción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(des, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTx2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTx1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTx1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTx2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            this.setVisible(false);
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ProductoXBodega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBAdicionar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        des.setEditable(true);
        banderaUpdate=0;
    }//GEN-LAST:event_jBModificarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        jBInicio.setEnabled(true);
        jBAnterior.setEnabled(true);
        jBProximo.setEnabled(true);
        jBUltimo.setEnabled(true);
        jBAdicionar.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscar.setEnabled(true);
        JBGrabar.setEnabled(false);
        JBCancelar.setEnabled(false);
        cod.setEditable(false);
        des.setEditable(false);
           try {
                
                if(!datos.wasNull()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBAdicionar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        cod.setEditable(true);
        des.setEditable(true);
        cod.setText("");
        des.setText("");
        banderaInsert=0;
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
       try {
                if(datos.first()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                    bandera2=0;
                }
                else{
                    cod.setText(datos.getString(""));
                    des.setText(datos.getString(""));
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoActionPerformed
        try {
            
                if(datos.last()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                    bandera1=0;
                }
                else{
                    cod.setText(datos.getString(""));
                    des.setText(datos.getString(""));
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBUltimoActionPerformed

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnteriorActionPerformed
        try {
          if(bandera1==1){
              datos.previous();
          }  
          if(bandera2==0){
              if(datos.previous()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                    bandera1=0;
                }
                else{
                  bandera2=1;   
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBAnteriorActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
       try {
           if(bandera2==1){
                boolean next = datos.next();
            }
             if(bandera1==0){
                if(datos.next()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                    bandera2=0;
                }
                else{
                    bandera1=1;
                }
             }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBProximoActionPerformed

    private void JBGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGrabarActionPerformed
      if(banderaInsert==0){
            if(cod.getText().isEmpty()){
                jLTx1.setText("El Campo de Codigo no puede quedar Vacio.");
                return;
            }
            if(des.getText().isEmpty()){
                jLTx2.setText("Ingrese una descripción.");
                return;
            }
            if(cod.getText().length()>3){
                jLTx1.setText("El codigo introducido excede los 3 caracteres.");
                return;
            }
            try {
                ps=ser.Querys("INSERT INTO inmar (codmar,desmar)values(?,?)");
                ps.setString(1,cod.getText());
                ps.setString(2,des.getText());
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT codmar,desmar FROM inmar ");
                datos = ser.Consultar(ps);                    
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode()==1062){
                    Frame f = JOptionPane.getFrameForComponent(this);
                    CodigoExistente dialog = new CodigoExistente(f, true);
                    dialog.setVisible(true);
                    cod.setText("");
                    des.setText("");
                    jLTx1.setText("");
                    jLTx2.setText("");
                    return;
                }
            }
            banderaInsert=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBAdicionar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            jLTx1.setText("");
            jLTx2.setText("");
      }
      if(banderaUpdate==0){
             if(des.getText().isEmpty()){
                 jLTx2.setText("Ingrese una descripción.");
                 return;
             }
             try {
                ps=ser.Querys("UPDATE inmar SET desmar = ? where codmar = ? ");
                ps.setString(1,des.getText());
                ps.setString(2,cod.getText());
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT codmar,desmar FROM inmar ");
                datos=ser.Consultar(ps);
                 try {
                    if(datos.next()){  
                        cod.setText(datos.getString("codmar"));
                        des.setText(datos.getString("desmar"));
                        bandera2=0;
                        bandera1=0;
                    }
                    } catch (SQLException ex) {
                        Logger.getLogger(LineaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                                
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            banderaUpdate=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBAdicionar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            TxCod.setEditable(true);
            jLTx2.setText("");
            
        }
    }//GEN-LAST:event_JBGrabarActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
       Frame f = JOptionPane.getFrameForComponent(this);
              BorrarFila dialog = new BorrarFila(f, true);
              dialog.setVisible(true);
              if(dialog.getReturnStatus()==BorrarFila.RET_OK){
              ps =ser.Querys("DELETE FROM inmar where codmar=?");
              try {
                  ps.setString(1,cod.getText());
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              try {
                  ser.InsBorrElim(ps);
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              ps=ser.Querys("SELECT * FROM inmar");
              try {
                 datos=ser.Consultar(ps);
                 if(datos.next()){
                    cod.setText(datos.getString("codmar"));
                    des.setText(datos.getString("desmar"));
                    bandera2=0;
                    bandera1=0;
                  
                 }
              } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                }                        
    }                 
    }//GEN-LAST:event_jBEliminarActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBGrabar;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField des;
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBProximo;
    private javax.swing.JButton jBUltimo;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLTx1;
    private javax.swing.JLabel jLTx2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
