/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.archivos;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JInternalFrame;

/**
 *
 * @author EQUIPO
 */
public class PrinciPAL extends javax.swing.JFrame {

    /**
     * Creates new form PrinciPAL
     */
    public PrinciPAL() {
        initComponents();
      
  
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskPanelP = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivos = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMCatalogoProductos = new javax.swing.JMenuItem();
        jMProductosBodega = new javax.swing.JMenuItem();
        jMBodegaSucursales = new javax.swing.JMenuItem();
        jMCatgoriaProductos = new javax.swing.JMenuItem();
        jMLineaProductos = new javax.swing.JMenuItem();
        jMTipoTransacciones = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem69 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem73 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem74 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem77 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DeskPanelP.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout DeskPanelPLayout = new javax.swing.GroupLayout(DeskPanelP);
        DeskPanelP.setLayout(DeskPanelPLayout);
        DeskPanelPLayout.setHorizontalGroup(
            DeskPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3829, Short.MAX_VALUE)
        );
        DeskPanelPLayout.setVerticalGroup(
            DeskPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/folder256.png"))); // NOI18N
        Archivos.setText("Archivos ");
        Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ArchivosMousePressed(evt);
            }
        });
        Archivos.add(jSeparator1);

        jMCatalogoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bag45.png"))); // NOI18N
        jMCatalogoProductos.setText("Catálogo de Productos ");
        jMCatalogoProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMCatalogoProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMCatalogoProductosMousePressed(evt);
            }
        });
        jMCatalogoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCatalogoProductosActionPerformed(evt);
            }
        });
        Archivos.add(jMCatalogoProductos);

        jMProductosBodega.setText("Productos por Bodega ");
        jMProductosBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProductosBodegaActionPerformed(evt);
            }
        });
        Archivos.add(jMProductosBodega);

        jMBodegaSucursales.setText("Bodegas o Sucursales");
        jMBodegaSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBodegaSucursalesActionPerformed(evt);
            }
        });
        Archivos.add(jMBodegaSucursales);

        jMCatgoriaProductos.setText("Categorias de Productos ");
        jMCatgoriaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCatgoriaProductosActionPerformed(evt);
            }
        });
        Archivos.add(jMCatgoriaProductos);

        jMLineaProductos.setText("Línea de Productos ");
        jMLineaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLineaProductosActionPerformed(evt);
            }
        });
        Archivos.add(jMLineaProductos);

        jMTipoTransacciones.setText("Tipos de Transacciones ");
        jMTipoTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTipoTransaccionesActionPerformed(evt);
            }
        });
        Archivos.add(jMTipoTransacciones);

        jMenuItem7.setText("Tipos de Compras");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem7);

        jMenuItem8.setText("Tipos de Ventas ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem8);

        jMenuItem9.setText("Marcas de Productos ");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem9);

        jMenuItem10.setText("Proveedores ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem10);

        jMenuItem11.setText("Clientes ");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem11);

        jMenuItem12.setText("Vendedores Internos ");
        Archivos.add(jMenuItem12);

        jMenuItem13.setText("Instituciones Bancarias ");
        Archivos.add(jMenuItem13);

        jMenuItem14.setText("Tarjetas de Credito");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem14);

        jMenuItem15.setText("Unidades de Medida ");
        Archivos.add(jMenuItem15);

        jMenuItem16.setText("Cajeros");
        Archivos.add(jMenuItem16);

        jMenuItem17.setText("Promociones");
        Archivos.add(jMenuItem17);
        Archivos.add(jSeparator2);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem18.setBackground(new java.awt.Color(204, 0, 51));
        jMenuItem18.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel22.png"))); // NOI18N
        jMenuItem18.setText("Salir     ");
        jMenuItem18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem18MousePressed(evt);
            }
        });
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuItem18);

        jMenuBar1.add(Archivos);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/setting5.png"))); // NOI18N
        jMenu2.setText("Procesos");
        jMenu2.add(jSeparator3);

        jMenuItem19.setText("Compras de Producto ");
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("Notas de Credito Proveedores");
        jMenu2.add(jMenuItem20);

        jMenuItem21.setText("Otras Transacciones");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem21);

        jMenuItem22.setText("Traslado entre Bodegas ");
        jMenu2.add(jMenuItem22);
        jMenu2.add(jSeparator4);

        jMenuItem23.setText("Cambio de Codigos ");
        jMenu2.add(jMenuItem23);
        jMenu2.add(jSeparator5);

        jMenuItem24.setText("Retaceos");
        jMenu2.add(jMenuItem24);
        jMenu2.add(jSeparator6);

        jMenuItem25.setText("Codigos de Barra");
        jMenu2.add(jMenuItem25);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart.png"))); // NOI18N
        jMenu3.setText("Ventas");

        jMenuItem26.setText("Facturacion pos Tactil");
        jMenu3.add(jMenuItem26);

        jMenuItem27.setText("Facturacion Manual ");
        jMenu3.add(jMenuItem27);

        jMenuItem28.setText("Notas de Crédito (Devoluciones)");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem28);

        jMenuItem29.setText("Descuentos ");
        jMenu3.add(jMenuItem29);

        jMenuItem30.setText("Notas de Debito ");
        jMenu3.add(jMenuItem30);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sheet3.png"))); // NOI18N
        jMenu4.setText("Consultas ");

        jMenuItem31.setText("Existencias");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem31);

        jMenuItem32.setText("Movimientos Mensuales");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem32);

        jMenuItem1.setText("Movimientos Historicos");
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Kardex");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notes27.png"))); // NOI18N
        jMenu5.setText("Resportes");

        jMenu1.setText("Listados Generales");

        jMenuItem3.setText("Catálogo de Productos ");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Productos por Bodega ");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Otros Listados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenu5.add(jMenu1);

        jMenu8.setText("Reportes de Ventas");

        jMenuItem6.setText("Ventas Diarias");
        jMenu8.add(jMenuItem6);

        jMenuItem33.setText("Ventas Por Cliente ");
        jMenu8.add(jMenuItem33);

        jMenuItem34.setText("Ventas por Producto");
        jMenu8.add(jMenuItem34);

        jMenuItem35.setText("Resumen de Ventas por Categoría de Productos ");
        jMenu8.add(jMenuItem35);

        jMenuItem36.setText("Resumen de Ventas por Linea de Productos ");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem36);
        jMenu8.add(jSeparator8);

        jMenuItem37.setText("Los X's Productos con mayor Venta ");
        jMenu8.add(jMenuItem37);

        jMenuItem38.setText("Los X's Productos con menor Venta ");
        jMenu8.add(jMenuItem38);
        jMenu8.add(jSeparator9);

        jMenuItem39.setText("Ventas por Vendedor");
        jMenu8.add(jMenuItem39);

        jMenuItem40.setText("Lista de Precios");
        jMenu8.add(jMenuItem40);

        jMenuItem41.setText("Ventas Por Sucursales ");
        jMenu8.add(jMenuItem41);

        jMenu5.add(jMenu8);

        jMenu9.setText("Reportes de Transacciones");

        jMenuItem42.setText("Datos Digitados ");
        jMenu9.add(jMenuItem42);

        jMenuItem43.setText("Resumen de Transacciones por grupo de productos ");
        jMenu9.add(jMenuItem43);

        jMenuItem44.setText("Resumen de Transacciones por linea de Productos ");
        jMenu9.add(jMenuItem44);

        jMenuItem45.setText("Resumen por Tipo de Transacciones ");
        jMenu9.add(jMenuItem45);

        jMenuItem46.setText("Kardex por Producto");
        jMenu9.add(jMenuItem46);

        jMenuItem47.setText("Kardex por Inventario-Producto");
        jMenu9.add(jMenuItem47);
        jMenu9.add(jSeparator10);

        jMenuItem48.setText("Compras por Categoria ");
        jMenu9.add(jMenuItem48);

        jMenuItem49.setText("Compras por Linea de Producto");
        jMenu9.add(jMenuItem49);

        jMenuItem50.setText("Compras Diarias ");
        jMenu9.add(jMenuItem50);

        jMenuItem51.setText("Compras por Proveedor ");
        jMenu9.add(jMenuItem51);

        jMenuItem52.setText("Compras por Producto");
        jMenu9.add(jMenuItem52);
        jMenu9.add(jSeparator11);

        jMenuItem53.setText("Entradas y Salidas de Inventario");
        jMenu9.add(jMenuItem53);

        jMenuItem54.setText("Consumo por producto");
        jMenu9.add(jMenuItem54);

        jMenu5.add(jMenu9);

        jMenu10.setText("Reportes de Existencias ");

        jMenuItem55.setText("Existencias Totales de Inventario");
        jMenu10.add(jMenuItem55);

        jMenuItem56.setText("Existencias por Bodega ");
        jMenu10.add(jMenuItem56);

        jMenuItem57.setText("Productos con Existencias menor del minimo");
        jMenu10.add(jMenuItem57);

        jMenuItem58.setText("Productos con Existencias Mayor al Máximo");
        jMenu10.add(jMenuItem58);

        jMenuItem59.setText("Comparativo de Costos ");
        jMenu10.add(jMenuItem59);

        jMenuItem60.setText("Resumen de existencias ");
        jMenu10.add(jMenuItem60);

        jMenu5.add(jMenu10);

        jMenu11.setText("Reportes de Inventario Fisico");

        jMenuItem61.setText("Listado Para Toma Física");
        jMenu11.add(jMenuItem61);

        jMenuItem62.setText("Datos Digitados de Toma Física");
        jMenu11.add(jMenuItem62);

        jMenuItem63.setText("Existencias Físicas");
        jMenu11.add(jMenuItem63);

        jMenuItem64.setText("Comparativo Inventario Fisico-Computo");
        jMenu11.add(jMenuItem64);

        jMenu5.add(jMenu11);
        jMenu5.add(jSeparator7);

        jMenu12.setText("Cortes Punto de Ventas ");

        jMenuItem65.setText("Cortes X's Diarios y Mensuales");
        jMenu12.add(jMenuItem65);

        jMenuItem66.setText("Cortes Z's Diarios y Mensuales");
        jMenu12.add(jMenuItem66);

        jMenu5.add(jMenu12);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download181.png"))); // NOI18N
        jMenu6.setText("Inventario Fisico");

        jMenuItem67.setText("Datos de Toma Física");
        jMenu6.add(jMenuItem67);

        jMenuItem68.setText("Modificar Doc. Toma Física");
        jMenu6.add(jMenuItem68);
        jMenu6.add(jSeparator12);

        jMenuItem69.setText("Generar Ajustes Por Diferencias ");
        jMenu6.add(jMenuItem69);
        jMenu6.add(jSeparator13);

        jMenuItem70.setText("Cierre Ultimo Inventario Físico");
        jMenu6.add(jMenuItem70);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repair17.png"))); // NOI18N
        jMenu7.setText("Administrar Sistema ");

        jMenuItem71.setText("Indexamiento de Archivos ");
        jMenu7.add(jMenuItem71);

        jMenuItem72.setText("Actualizacion de Existencias ");
        jMenu7.add(jMenuItem72);
        jMenu7.add(jSeparator14);

        jMenuItem73.setText("Cierre Mensual");
        jMenu7.add(jMenuItem73);
        jMenu7.add(jSeparator15);

        jMenuItem74.setText("Puntos de Facturación o Cajas ");
        jMenu7.add(jMenuItem74);
        jMenu7.add(jSeparator16);

        jMenuItem75.setText("Clasificacion de Inventario");
        jMenu7.add(jMenuItem75);

        jMenuItem76.setText("Fijar Maximos y Minimos ");
        jMenu7.add(jMenuItem76);
        jMenu7.add(jSeparator17);

        jMenuItem77.setText("Parametros de Proceso");
        jMenu7.add(jMenuItem77);
        jMenu7.add(jSeparator18);

        jMenuItem78.setText("Exportar Archivos");
        jMenu7.add(jMenuItem78);

        jMenuItem79.setText("Importar Archivos ");
        jMenu7.add(jMenuItem79);

        jMenuBar1.add(jMenu7);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book244.png"))); // NOI18N
        jMenu13.setText("Ayuda");

        jMenuItem80.setText("Licencia ");
        jMenu13.add(jMenuItem80);

        jMenuItem81.setText("Acerca de Zeta Sistemas");
        jMenu13.add(jMenuItem81);

        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskPanelP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskPanelP, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCatalogoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCatalogoProductosActionPerformed
       CatalogoProduc ventanaP = new CatalogoProduc();
       DeskPanelP.add(ventanaP);
       try{
            ventanaP.setSelected(true);
            ventanaP.setMaximum(true);
       }catch (java.beans.PropertyVetoException e) {}
       ventanaP.setVisible(true);
        
    }//GEN-LAST:event_jMCatalogoProductosActionPerformed

    private void jMLineaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLineaProductosActionPerformed
       LineaDProductos ventanaLP = new LineaDProductos();
        centrarPantallaInternal(ventanaLP);
       
       ventanaLP.setVisible(true); 
    }//GEN-LAST:event_jMLineaProductosActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       Proveedores ventanaP = new Proveedores();
        centrarPantallaInternal(ventanaP);
       
       ventanaP.setVisible(true); 
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMCatalogoProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCatalogoProductosMouseClicked

    }//GEN-LAST:event_jMCatalogoProductosMouseClicked

    private void jMCatalogoProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCatalogoProductosMousePressed
 
    }//GEN-LAST:event_jMCatalogoProductosMousePressed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem18MousePressed
      System.exit(0); 
    }//GEN-LAST:event_jMenuItem18MousePressed

    private void ArchivosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivosMousePressed
       
       
       
    }//GEN-LAST:event_ArchivosMousePressed

    private void jMProductosBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProductosBodegaActionPerformed
       ProductoXBodega ventanaPB = new ProductoXBodega();
        centrarPantallaInternal(ventanaPB);
       ventanaPB.setVisible(true);
    }//GEN-LAST:event_jMProductosBodegaActionPerformed

    private void jMBodegaSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBodegaSucursalesActionPerformed
       BodegasOSucursales ventanaBS = new BodegasOSucursales();
       centrarPantallaInternal(ventanaBS);
       ventanaBS.setVisible(true);
    }//GEN-LAST:event_jMBodegaSucursalesActionPerformed

    private void jMCatgoriaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCatgoriaProductosActionPerformed
       CategoriaDProductos ventanaCP = new CategoriaDProductos();
       centrarPantallaInternal(ventanaCP);
       ventanaCP.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMCatgoriaProductosActionPerformed

    private void jMTipoTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTipoTransaccionesActionPerformed
        TipoTransaccion ventanaTP = new TipoTransaccion();
        centrarPantallaInternal(ventanaTP);
        ventanaTP.setVisible(true);
    }//GEN-LAST:event_jMTipoTransaccionesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TipoCompra ventanaTC = new TipoCompra();
        centrarPantallaInternal(ventanaTC);
        ventanaTC.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        TipoVenta ventanaTV = new TipoVenta();
        centrarPantallaInternal(ventanaTV);
        ventanaTV.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        MarcasProducto ventanaMP = new MarcasProducto();
        centrarPantallaInternal(ventanaMP);
        ventanaMP.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Client3s ventanaCL = new Client3s();
        centrarPantallaInternal(ventanaCL);
        ventanaCL.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed
    public void centrarPantallaInternal(JInternalFrame ventana){
        int x =(DeskPanelP.getWidth()/2)-ventana.getWidth()/2;
        int y =(DeskPanelP.getHeight()/2)-ventana.getHeight()/2;
        if(ventana.isShowing()){
            ventana.setLocation(x, y);
        }else{
            DeskPanelP.add(ventana);
            ventana.setLocation(x, y);
            ventana.setVisible(true);
        } 
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrinciPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrinciPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrinciPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrinciPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrinciPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivos;
    public static javax.swing.JDesktopPane DeskPanelP;
    private javax.swing.JMenuItem jMBodegaSucursales;
    private javax.swing.JMenuItem jMCatalogoProductos;
    private javax.swing.JMenuItem jMCatgoriaProductos;
    private javax.swing.JMenuItem jMLineaProductos;
    private javax.swing.JMenuItem jMProductosBodega;
    private javax.swing.JMenuItem jMTipoTransacciones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
