/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.archivos;

import ejemplo.servicio;
import static interfaz.archivos.CategoriaDProductos.TxCod;
import static interfaz.archivos.CategoriaDProductos.TxCuenta;
import static interfaz.archivos.CategoriaDProductos.TxDes;
import java.awt.Frame;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class Proveedores extends javax.swing.JInternalFrame {
     private ResultSet datos;
     private ResultSet pais;
     private ResultSet departamento;
     private ResultSet ciudad;
     private int bandera1=0;
     private int bandera2=0;
     private int banderaInsert=1;
     private int banderaUpdate=1;
     private PreparedStatement ps;
     private servicio ser;
     private int bandPais =0;
    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
         ser=new servicio();
         jCPais.removeAllItems();
         jCDepar.removeAllItems();
         jCCiudad.removeAllItems();
         BG1.add(jBSi);
         BG1.add(jBNo);
         jBNo.setSelected(true);
         try {
            
             ps = ser.Querys("SELECT p.codpro, p.nomprov, p.dirprov, c.codciu, c.desciu, d.desdpto, pa.despais, p.telprov, p.faxprov, p.email, p.numreg, p.numnit, p.giro, p.contacto, p.plazo, p.grancontri from cppro as p,ccciu as c,ccdpto as d,ccpais as pa where p.codciu = c.codciu and c.coddpto = d.coddpto and d.codpais = pa.codpais ");
             datos=ser.Consultar(ps);
             if(datos.next()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.addItem(datos.getString("despais"));    
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                 
                 
             }
             
         } catch (SQLException ex) {
             Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
         }
          jTCodProv.setEditable(false);
          jTDesProv.setEditable(false);
          jTDirProv.setEditable(false);
          
          jTTel.setEditable(false);
          jTFax.setEditable(false);
          jTEmail.setEditable(false);
          jTRegis.setEditable(false);
          jTNIT.setEditable(false);
          jTGiro.setEditable(false);
          jTCont.setEditable(false);
          jTPlazoPago.setEditable(false);
          jBSi.setEnabled(false);
          jBNo.setEnabled(false);
         
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG1 = new javax.swing.ButtonGroup();
        jTP1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTDirProv = new javax.swing.JTextField();
        jTEmail = new javax.swing.JTextField();
        jTTel = new javax.swing.JTextField();
        jTGiro = new javax.swing.JTextField();
        jTRegis = new javax.swing.JTextField();
        jTCont = new javax.swing.JTextField();
        jTNIT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jBSi = new javax.swing.JRadioButton();
        jBNo = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jTPlazoPago = new javax.swing.JTextField();
        jCPais = new javax.swing.JComboBox();
        jCDepar = new javax.swing.JComboBox();
        jCCiudad = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProvProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCodProv = new javax.swing.JTextField();
        jTDesProv = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jBInicio = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        JBGrabar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jBModCost = new javax.swing.JButton();
        jLTx1 = new javax.swing.JLabel();
        jLTx2 = new javax.swing.JLabel();

        setTitle("PROVEEDORES");

        jPanel1.setAutoscrolls(true);

        jLabel3.setText("Dirección");

        jLabel4.setText("Pais");

        jLabel5.setText("Departamento");

        jLabel6.setText("E-mail");

        jLabel7.setText("N° Telefono");

        jLabel8.setText("Giro ó A.E");

        jLabel9.setText("N° de Registro");

        jLabel10.setText("Contacto");

        jLabel11.setText("N° NIT");

        jTGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTGiroActionPerformed(evt);
            }
        });

        jLabel12.setText("N° Fax");

        jLabel13.setText("Gran Contribuyente");

        jBSi.setText("Si");

        jBNo.setText("No");

        jLabel14.setText("Plazo de pago");

        jCPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPaisActionPerformed(evt);
            }
        });
        jCPais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCPaisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCPaisFocusLost(evt);
            }
        });

        jCDepar.setMaximumRowCount(9);
        jCDepar.setAutoscrolls(true);
        jCDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDeparActionPerformed(evt);
            }
        });
        jCDepar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCDeparFocusGained(evt);
            }
        });

        jCCiudad.setAutoscrolls(true);
        jCCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCCiudadFocusGained(evt);
            }
        });

        jLabel15.setText("Ciudad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCont)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTEmail)
                                    .addComponent(jTGiro)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTTel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBNo))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(47, 47, 47)
                                        .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTPlazoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15)
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFax, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDirProv, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCPais, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTDirProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jCCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jBSi)
                    .addComponent(jBNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTPlazoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTP1.addTab("DATOS GENERALES", jPanel1);

        jTProvProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Unidad de Presentacion", "Existencias", "Costo Digitado", "Pedido"
            }
        ));
        jScrollPane1.setViewportView(jTProvProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jTP1.addTab("LISTADO DE PRECIOS", jPanel2);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jTCodProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodProvActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jBInicio.setText("Inicio");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBAnterior.setText("Anterior");
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        jBProximo.setText("Próximo");
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });

        jBUltimo.setText("Ultimo");
        jBUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBUltimo)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInicio)
                    .addComponent(jBAnterior)
                    .addComponent(jBProximo)
                    .addComponent(jBUltimo))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jBNuevo.setText("Adicionar");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        JBGrabar.setText("Grabar");
        JBGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGrabarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscar)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBEliminar)
                    .addComponent(JBGrabar)
                    .addComponent(JBCancelar)
                    .addComponent(jBBuscar)
                    .addComponent(jBModificar))
                .addContainerGap())
        );

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Salir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jBModCost.setText("Modificar Costo Digitado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBModCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTx1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLTx2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTCodProv, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTDesProv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTx1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLTx2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTCodProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDesProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBModCost)
                            .addComponent(jButton11))))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        
          jTCodProv.setEditable(true);
          jTDesProv.setEditable(true);
          jTDirProv.setEditable(true);
          jTTel.setEditable(true);
          jTFax.setEditable(true);
          jTEmail.setEditable(true);
          jTRegis.setEditable(true);
          jTNIT.setEditable(true);
          jTGiro.setEditable(true);
          jTCont.setEditable(true);
          jTPlazoPago.setEditable(true);
          jBSi.setEnabled(true);
          jBNo.setEnabled(true);
          jCPais.removeAllItems();
          jCDepar.removeAllItems();
          jCCiudad.removeAllItems();
             jTCodProv.setText("");
             jTDesProv.setText("");
             jTDirProv.setText("");
             jCPais.removeAllItems();    
             jCDepar.removeAllItems();
             jCCiudad.removeAllItems();
             jTTel.setText("");
             jTFax.setText("");
             jTEmail.setText("");
             jTRegis.setText("");
             jTNIT.setText("");
             jTGiro.setText("");
             jTCont.setText("");
             jTPlazoPago.setText("");
             jBNo.setSelected(true);
             bandPais=1;
             banderaInsert=0;
            if(bandPais==1){
        try {
             ps = ser.Querys("SELECT * FROM Ccpais");
             pais = ser.Consultar(ps);
             while(pais.next()){
              jCPais.addItem(pais.getString("despais"));
             }
             jCDepar.removeAllItems();
             jCCiudad.removeAllItems();
         } catch (SQLException ex) {
             Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        jBInicio.setEnabled(true);
        jBAnterior.setEnabled(true);
        jBProximo.setEnabled(true);
        jBUltimo.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscar.setEnabled(true);
        JBGrabar.setEnabled(false);
        JBCancelar.setEnabled(false);
        bandPais=0;
        try {
                
                if(!datos.wasNull()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.addItem(datos.getString("despais"));    
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        jTCodProv.setEditable(false);
          jTDesProv.setEditable(false);
          jTDirProv.setEditable(false);
          
          jTTel.setEditable(false);
          jTFax.setEditable(false);
          jTEmail.setEditable(false);
          jTRegis.setEditable(false);
          jTNIT.setEditable(false);
          jTGiro.setEditable(false);
          jTCont.setEditable(false);
          jTPlazoPago.setEditable(false);
          jBSi.setEnabled(false);
          jBNo.setEnabled(false);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        JBGrabar.setEnabled(true);
        JBCancelar.setEnabled(true);
        jBInicio.setEnabled(false);
        jBAnterior.setEnabled(false);
        jBProximo.setEnabled(false);
        jBUltimo.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        banderaUpdate=0;
        jTDesProv.setEditable(true);
        jTDirProv.setEditable(true);
        jTTel.setEditable(true);
        jTFax.setEditable(true);
        jTEmail.setEditable(true);
        jTRegis.setEditable(true);
        jTNIT.setEditable(true);
        jTGiro.setEditable(true);
        jTCont.setEditable(true);
        jTPlazoPago.setEditable(true);
        jBSi.setEnabled(true);
        jBNo.setEnabled(true);
        bandPais=1;
        jCPais.removeAllItems();
            if(bandPais==1){
        try {
             ps = ser.Querys("SELECT * FROM Ccpais");
             pais = ser.Consultar(ps);
             while(pais.next()){
              jCPais.addItem(pais.getString("despais"));
             }
             jCDepar.removeAllItems();
             jCCiudad.removeAllItems();
         } catch (SQLException ex) {
             Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            this.setVisible(false);
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ProductoXBodega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTGiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGiroActionPerformed

    private void jTCodProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodProvActionPerformed

    private void jCPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPaisActionPerformed
     if(bandPais==1){
        try {
             int index=jCPais.getSelectedIndex();
             if(index==-1){
                 return;
             }
             jCDepar.removeAllItems();
             pais.absolute(index+1);
             System.out.println(index);
             int valor = pais.getInt("codpais");
            
             ps=ser.Querys("SELECT * FROM Ccdpto where codpais = ?");
             ps.setInt(1,valor);
             departamento = ser.Consultar(ps);
             while(departamento.next()){
              jCDepar.addItem(departamento.getString("desdpto"));
             }
             jCCiudad.removeAllItems();
         } catch (SQLException ex) {
             Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
         }
        } 
    }//GEN-LAST:event_jCPaisActionPerformed

    private void jCDeparFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCDeparFocusGained
        
    }//GEN-LAST:event_jCDeparFocusGained

    private void jBUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoActionPerformed
       try {
                if(datos.last()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.removeAllItems();
                 jCPais.addItem(datos.getString("despais")); 
                 jCDepar.removeAllItems();
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.removeAllItems();
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                    bandera1=0;
                }
                else{
                     jTCodProv.setText("");
                 jTDesProv.setText("");
                 jTDirProv.setText("");
                 jCPais.removeAllItems();    
                 jCDepar.removeAllItems();
                 jCCiudad.removeAllItems();
                 jTTel.setText("");
                 jTFax.setText("");
                 jTEmail.setText("");
                 jTRegis.setText("");
                 jTNIT.setText("");
                 jTGiro.setText("");
                 jTCont.setText("");
                 jTPlazoPago.setText("");
                 jBNo.setSelected(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBUltimoActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
       try {
                if(datos.first()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.removeAllItems();
                 jCPais.addItem(datos.getString("despais")); 
                 jCDepar.removeAllItems();
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.removeAllItems();
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                    bandera2=0;
                }
                else{
                 jTCodProv.setText("");
                 jTDesProv.setText("");
                 jTDirProv.setText("");
                 jCPais.removeAllItems();    
                 jCDepar.removeAllItems();
                 jCCiudad.removeAllItems();
                 jTTel.setText("");
                 jTFax.setText("");
                 jTEmail.setText("");
                 jTRegis.setText("");
                 jTNIT.setText("");
                 jTGiro.setText("");
                 jTCont.setText("");
                 jTPlazoPago.setText("");
                 jBNo.setSelected(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnteriorActionPerformed
        try { 
            if(bandera1==1){
                datos.previous();
            }
            if(bandera2==0){
                if(datos.previous()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.removeAllItems();
                 jCPais.addItem(datos.getString("despais")); 
                 jCDepar.removeAllItems();
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.removeAllItems();
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                    bandera1=0;
                }
                else{
                  bandera2=1;   
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jBAnteriorActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
       try {
             if(bandera2==1){
                 datos.next();
             }
             if(bandera1==0){
                if(datos.next()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.removeAllItems();
                 jCPais.addItem(datos.getString("despais")); 
                 jCDepar.removeAllItems();
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.removeAllItems();
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                    bandera2=0;
                }
                else{
                    bandera1=1;
                }
             }
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBProximoActionPerformed

    private void jCPaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCPaisFocusGained
        jCDepar.removeAllItems();
         
    }//GEN-LAST:event_jCPaisFocusGained

    private void jCDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDeparActionPerformed
       if(bandPais==1){
        try {
            
             int index=jCDepar.getSelectedIndex();
             if(index==-1){
                 return;
             }
              jCCiudad.removeAllItems();
             departamento.absolute(index+1);
             System.out.println(index);
             int valor = departamento.getInt("coddpto");
             System.out.println(valor);
             ps=ser.Querys("SELECT * FROM Ccciu where coddpto = ? order by desciu");
             ps.setInt(1,valor);
             ciudad = ser.Consultar(ps);
             while(ciudad.next()){
              jCCiudad.addItem(ciudad.getString("desciu"));
             }
         } catch (SQLException ex) {
             Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
         }
     }
    }//GEN-LAST:event_jCDeparActionPerformed

    private void jCPaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCPaisFocusLost
    
    }//GEN-LAST:event_jCPaisFocusLost

    private void jCCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCCiudadFocusGained
     
    }//GEN-LAST:event_jCCiudadFocusGained

    private void JBGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGrabarActionPerformed
      if(banderaInsert==0){
            if(jTCodProv.getText().isEmpty()){
                jLTx1.setText("El Campo de Codigo no puede quedar Vacio.");
                return;
            }
            if(jTDesProv.getText().isEmpty()){
                jLTx2.setText("Ingrese una descripción.");
                return;
            }
            if(jTCodProv.getText().length()>3){
                jLTx1.setText("El codigo introducido excede los 3 caracteres.");
                return;
            }
            try {
                ps=ser.Querys("INSERT INTO cppro (codpro,nomprov,dirprov,codciu,telprov,faxprov,email,numreg,numnit,giro,contacto,plazo,grancontri)values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1,jTCodProv.getText());
                ps.setString(2,jTDesProv.getText());
                ps.setString(3,jTDirProv.getText());
                int pos =jCCiudad.getSelectedIndex();
                
                ciudad.absolute(pos+1);
                String cad = ciudad.getString("codciu");
                ps.setString(4,cad);
                ps.setString(5,jTTel.getText());
                ps.setString(6,jTFax.getText());
                ps.setString(7,jTEmail.getText());
                ps.setString(8,jTRegis.getText());
                ps.setString(9,jTNIT.getText());
                ps.setString(10,jTGiro.getText());
                ps.setString(11,jTCont.getText());
                int plazo;
                if(jTPlazoPago.getText().isEmpty())ps.setInt(12,0);
                else ps.setInt(12,Integer.parseInt(jTPlazoPago.getText()));
                boolean bs;
                if(jBSi.isSelected()) bs=true;
                else bs=false;  
                ps.setBoolean(13,bs);
                
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT p.codpro, p.nomprov, p.dirprov, c.codciu, c.desciu, d.desdpto, pa.despais, p.telprov, p.faxprov, p.email, p.numreg, p.numnit, p.giro, p.contacto, p.plazo, p.grancontri from cppro as p,ccciu as c,ccdpto as d,ccpais as pa where p.codciu = c.codciu and c.coddpto = d.coddpto and d.codpais = pa.codpais ");
                datos = ser.Consultar(ps);                    
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode()==1062){
                    Frame f = JOptionPane.getFrameForComponent(this);
                    CodigoExistente dialog = new CodigoExistente(f, true);
                    dialog.setVisible(true);
                    return;
                }
            }
            banderaInsert=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBNuevo.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            jLTx1.setText("");
            jLTx2.setText("");
             jTCodProv.setEditable(false);
          jTDesProv.setEditable(false);
          jTDirProv.setEditable(false);
          jTTel.setEditable(false);
          jTFax.setEditable(false);
          jTEmail.setEditable(false);
          jTRegis.setEditable(false);
          jTNIT.setEditable(false);
          jTGiro.setEditable(false);
          jTCont.setEditable(false);
          jTPlazoPago.setEditable(false);
          jBSi.setEnabled(false);
          jBNo.setEnabled(false);
        }
      if(banderaUpdate==0){
             if(jLTx2.getText().isEmpty()){
                 jLTx2.setText("Ingrese una descripción.");
                 return;
             }
             try {
                ps=ser.Querys("UPDATE cppro SET nomprov =?,dirprov=?,codciu=?,telprov=?,faxprov=?,email=?,numreg=?,numnit=?,giro=?,contacto=?,plazo=?,grancontri=? where codpro = ? ");
                
                ps.setString(1,jTDesProv.getText());
                ps.setString(2,jTDirProv.getText());
                int pos =jCCiudad.getSelectedIndex();
                
                ciudad.absolute(pos+1);
                String cad = ciudad.getString("codciu");
                ps.setString(3,cad);
                ps.setString(4,jTTel.getText());
                ps.setString(5,jTFax.getText());
                ps.setString(6,jTEmail.getText());
                ps.setString(7,jTRegis.getText());
                ps.setString(8,jTNIT.getText());
                ps.setString(9,jTGiro.getText());
                ps.setString(10,jTCont.getText());
                if(jTPlazoPago.getText().isEmpty())ps.setInt(11,0);
                else ps.setInt(11,Integer.parseInt(jTPlazoPago.getText()));
                boolean bs;
                bs = jBSi.isSelected();  
                ps.setBoolean(12,bs);
                ps.setString(13,jTCodProv.getText());
                
                ser.InsBorrElim(ps);
                ps=ser.Querys("SELECT p.codpro, p.nomprov, p.dirprov, c.codciu, c.desciu, d.desdpto, pa.despais, p.telprov, p.faxprov, p.email, p.numreg, p.numnit, p.giro, p.contacto, p.plazo, p.grancontri from cppro as p,ccciu as c,ccdpto as d,ccpais as pa where p.codciu = c.codciu and c.coddpto = d.coddpto and d.codpais = pa.codpais ");
                datos=ser.Consultar(ps);
                bandera1=0;                
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            banderaUpdate=1;
            jBInicio.setEnabled(true);
            jBAnterior.setEnabled(true);
            jBProximo.setEnabled(true);
            jBUltimo.setEnabled(true);
            jBNuevo.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBBuscar.setEnabled(true);
            JBGrabar.setEnabled(false);
            JBCancelar.setEnabled(false);
            TxCod.setEditable(true);
            jLTx2.setText("");
            
        }
    }//GEN-LAST:event_JBGrabarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
              BorrarFila dialog = new BorrarFila(f, true);
              dialog.setVisible(true);
              if(dialog.getReturnStatus()==dialog.RET_OK){
              ps =ser.Querys("DELETE FROM cppro where codpro=?");
              try {
                  ps.setString(1,jTCodProv.getText().toString());
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              try {
                  ser.InsBorrElim(ps);
              } catch (SQLException ex) {
                  Logger.getLogger(CategoriaDProductos.class.getName()).log(Level.SEVERE, null, ex);
              }
              jCPais.removeAllItems();
              jCDepar.removeAllItems();
              jCCiudad.removeAllItems();
             try {
            
             ps = ser.Querys("SELECT p.codpro, p.nomprov, p.dirprov, c.codciu, c.desciu, d.desdpto, pa.despais, p.telprov, p.faxprov, p.email, p.numreg, p.numnit, p.giro, p.contacto, p.plazo, p.grancontri from cppro as p,ccciu as c,ccdpto as d,ccpais as pa where p.codciu = c.codciu and c.coddpto = d.coddpto and d.codpais = pa.codpais ");
             datos=ser.Consultar(ps);
             if(datos.next()){
                 jTCodProv.setText(datos.getString("codpro"));
                 jTDesProv.setText(datos.getString("nomprov"));
                 jTDirProv.setText(datos.getString("dirprov"));
                 jCPais.addItem(datos.getString("despais"));    
                 jCDepar.addItem(datos.getString("desdpto"));
                 jCCiudad.addItem(datos.getString("desciu"));
                 jTTel.setText(datos.getString("telprov"));
                 jTFax.setText(datos.getString("faxprov"));
                 jTEmail.setText(datos.getString("email"));
                 jTRegis.setText(datos.getString("numreg"));
                 jTNIT.setText(datos.getString("numnit"));
                 jTGiro.setText(datos.getString("giro"));
                 jTCont.setText(datos.getString("contacto"));
                 jTPlazoPago.setText(datos.getString("plazo"));
                 if(datos.getBoolean("grancontri")){
                     jBSi.setSelected(true);
                 }
                 else jBNo.setSelected(true);
                 
                 
             }
             
         } catch (SQLException ex) {
             Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
         }
          jTCodProv.setEditable(false);
          jTDesProv.setEditable(false);
          jTDirProv.setEditable(false);
          
          jTTel.setEditable(false);
          jTFax.setEditable(false);
          jTEmail.setEditable(false);
          jTRegis.setEditable(false);
          jTNIT.setEditable(false);
          jTGiro.setEditable(false);
          jTCont.setEditable(false);
          jTPlazoPago.setEditable(false);
          jBSi.setEnabled(false);
          jBNo.setEnabled(false);
         
          
                    }
    }//GEN-LAST:event_jBEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG1;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBGrabar;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBModCost;
    private javax.swing.JButton jBModificar;
    private javax.swing.JRadioButton jBNo;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBProximo;
    private javax.swing.JRadioButton jBSi;
    private javax.swing.JButton jBUltimo;
    private javax.swing.JButton jButton11;
    private javax.swing.JComboBox jCCiudad;
    private javax.swing.JComboBox jCDepar;
    private javax.swing.JComboBox jCPais;
    private javax.swing.JLabel jLTx1;
    private javax.swing.JLabel jLTx2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodProv;
    private javax.swing.JTextField jTCont;
    private javax.swing.JTextField jTDesProv;
    private javax.swing.JTextField jTDirProv;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTFax;
    private javax.swing.JTextField jTGiro;
    private javax.swing.JTextField jTNIT;
    private javax.swing.JTabbedPane jTP1;
    private javax.swing.JTextField jTPlazoPago;
    private javax.swing.JTable jTProvProductos;
    private javax.swing.JTextField jTRegis;
    private javax.swing.JTextField jTTel;
    // End of variables declaration//GEN-END:variables
}
